import type { Platform, StateSnapshot } from './types'

export type ExportFormat = 'markdown' | 'notion' | 'copy-bundle' | 'social-kit'

const PLATFORM_LABELS: Record<Platform, string> = {
  twitter: 'Twitter / X Thread',
  linkedin: 'LinkedIn Post',
  newsletter: 'Newsletter Digest',
}

function getTopic(snapshot: StateSnapshot): string {
  return snapshot.parsed_summary?.main_topic?.trim() || 'Untitled DraftLoop Run'
}

function getDraftContent(snapshot: StateSnapshot, platform: Platform): string {
  return snapshot[`${platform}_draft`]?.content?.trim() || 'Not available'
}

function getScore(snapshot: StateSnapshot, platform: Platform): number | null {
  return snapshot[`${platform}_feedback`]?.score ?? null
}

function getSuggestion(snapshot: StateSnapshot, platform: Platform): string {
  return snapshot[`${platform}_feedback`]?.suggestion?.trim() || 'No critic suggestion recorded.'
}

function getPlatformSection(snapshot: StateSnapshot, platform: Platform): string {
  const label = PLATFORM_LABELS[platform]
  const score = getScore(snapshot, platform)
  const scoreLine = score ? `Score: ${score}/10` : 'Score: N/A'

  return [
    `## ${label}`,
    scoreLine,
    `Critic Note: ${getSuggestion(snapshot, platform)}`,
    '',
    getDraftContent(snapshot, platform),
  ].join('\n')
}

function buildMarkdown(snapshot: StateSnapshot): string {
  const topic = getTopic(snapshot)
  const tone = snapshot.parsed_summary?.tone || 'Unknown'
  const keyPoints = snapshot.parsed_summary?.key_points ?? []

  return [
    `# ${topic}`,
    '',
    `Generated by DraftLoop`,
    '',
    `## Summary`,
    `- Tone: ${tone}`,
    `- Thread ID: ${snapshot.thread_id}`,
    ...(keyPoints.length ? ['', '## Key Points', ...keyPoints.map((point) => `- ${point}`)] : []),
    '',
    getPlatformSection(snapshot, 'twitter'),
    '',
    getPlatformSection(snapshot, 'linkedin'),
    '',
    getPlatformSection(snapshot, 'newsletter'),
    '',
  ].join('\n')
}

function buildNotion(snapshot: StateSnapshot): string {
  const topic = getTopic(snapshot)
  const keyPoints = snapshot.parsed_summary?.key_points ?? []

  return [
    `# ${topic}`,
    '',
    `> Imported from DraftLoop`,
    '',
    '## Repurposing Brief',
    `- Main topic: ${topic}`,
    `- Tone: ${snapshot.parsed_summary?.tone || 'Unknown'}`,
    ...(keyPoints.length ? keyPoints.map((point) => `- ${point}`) : ['- No key points recorded']),
    '',
    '---',
    '',
    '## Twitter / X Thread',
    getDraftContent(snapshot, 'twitter'),
    '',
    '---',
    '',
    '## LinkedIn Post',
    getDraftContent(snapshot, 'linkedin'),
    '',
    '---',
    '',
    '## Newsletter Digest',
    getDraftContent(snapshot, 'newsletter'),
    '',
  ].join('\n')
}

function buildCopyBundle(snapshot: StateSnapshot): string {
  return [
    `DRAFTLOOP COPY BUNDLE`,
    `${getTopic(snapshot)}`,
    '',
    `TWITTER / X`,
    getDraftContent(snapshot, 'twitter'),
    '',
    `LINKEDIN`,
    getDraftContent(snapshot, 'linkedin'),
    '',
    `NEWSLETTER`,
    getDraftContent(snapshot, 'newsletter'),
    '',
    `END OF BUNDLE`,
  ].join('\n')
}

function buildSocialKit(snapshot: StateSnapshot): string {
  const topic = getTopic(snapshot)

  return [
    `DRAFTLOOP SOCIAL POSTING KIT`,
    '',
    `Campaign Topic: ${topic}`,
    `Tone: ${snapshot.parsed_summary?.tone || 'Unknown'}`,
    '',
    'POSTING ORDER',
    '1. Publish the LinkedIn post for context.',
    '2. Follow with the Twitter / X thread to drive conversation.',
    '3. Send the newsletter digest as the deep-dive recap.',
    '',
    'TWITTER / X THREAD',
    getDraftContent(snapshot, 'twitter'),
    '',
    'LINKEDIN POST',
    getDraftContent(snapshot, 'linkedin'),
    '',
    'NEWSLETTER DIGEST',
    getDraftContent(snapshot, 'newsletter'),
    '',
    'CRITIC SNAPSHOT',
    `- X: ${getSuggestion(snapshot, 'twitter')}`,
    `- LinkedIn: ${getSuggestion(snapshot, 'linkedin')}`,
    `- Newsletter: ${getSuggestion(snapshot, 'newsletter')}`,
    '',
  ].join('\n')
}

export function buildExportContent(snapshot: StateSnapshot, format: ExportFormat): string {
  switch (format) {
    case 'markdown':
      return buildMarkdown(snapshot)
    case 'notion':
      return buildNotion(snapshot)
    case 'copy-bundle':
      return buildCopyBundle(snapshot)
    case 'social-kit':
      return buildSocialKit(snapshot)
  }
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'draftloop-export'
}

export function getExportFilename(snapshot: StateSnapshot, format: ExportFormat): string {
  const base = slugify(getTopic(snapshot))
  const suffixMap: Record<ExportFormat, string> = {
    markdown: 'markdown-pack.md',
    notion: 'notion-ready.md',
    'copy-bundle': 'copy-bundle.txt',
    'social-kit': 'social-posting-kit.txt',
  }

  return `${base}-${suffixMap[format]}`
}

export function downloadExport(snapshot: StateSnapshot, format: ExportFormat) {
  const content = buildExportContent(snapshot, format)
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = getExportFilename(snapshot, format)
  document.body.appendChild(anchor)
  anchor.click()
  document.body.removeChild(anchor)
  URL.revokeObjectURL(url)
}

